import img1 from '../userImages/1.jpg';
import img2 from '../userImages/2.jpg';
import img3 from '../userImages/3.jpg';
import img4 from '../userImages/4.jpg';
import img5 from '../userImages/5.jpg';
import img6 from '../userImages/6.jpg';
import img7 from '../userImages/7.jpg';
import img8 from '../userImages/8.jpg';
import img9 from '../userImages/9.jpg';
import img10 from '../userImages/10.jpg';
import img11 from '../userImages/11.jpg';
import img12 from '../userImages/12.jpg';
import img17 from '../userImages/17.jpg';
import img14 from '../userImages/14.jpg';
import img15 from '../userImages/15.jpg';
import img16 from '../userImages/16.jpg';
import img18 from '../userImages/18.jpg';
import img19 from '../userImages/19.jpg';

export {img1, img2, img3, img4, img5, img6, img7, img8, img9, img10, img11, img12, img17, img14, img15, img16, img18, img19};